import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:luxora_ai/models/lux_place.dart';

/// Loads the bundled OpenStreetMap places asset
/// (`assets/places/osm_places.json`, generated by
/// `tool/import_osm_places.dart`). Keyless and offline — the file ships in the
/// app bundle. Rows use the same shape as Supabase `places` rows so they map
/// through [LuxPlace.fromSupabaseRow].
class PlacesAssetRepository {
  const PlacesAssetRepository._();

  static const _assetPath = 'assets/places/osm_places.json';

  static Future<List<LuxPlace>> loadOsmPlaces() async {
    try {
      final raw = await rootBundle.loadString(_assetPath);
      if (raw.trim().isEmpty) return const [];
      final decoded = jsonDecode(raw);
      if (decoded is! List) return const [];
      return decoded
          .whereType<Map<String, dynamic>>()
          .map(LuxPlace.fromSupabaseRow)
          .whereType<LuxPlace>()
          .toList();
    } on FlutterError {
      // Asset not declared / not present yet — fine before first import.
      return const [];
    } catch (e, st) {
      debugPrint('PlacesAssetRepository: $e\n$st');
      return const [];
    }
  }
}
