import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve('.');
const targets = [
  'lib/data/curated_places_catalog.dart',
  'lib/data/curated_places_attractions.dart',
  'lib/data/curated_places_major_attractions.dart',
  'lib/data/feed_items.dart',
  'lib/data/gem_discoveries.dart',
  'lib/data/saved_trips.dart',
  'lib/data/trip_plans.dart',
  'lib/services/attraction_detail_repository.dart',
];

const outPath = path.join(root, 'lib/l10n/catalog_translations_ru.dart');

const FIELD_PATTERNS = [
  /\btitle:\s*'((?:\\.|[^'\\])*)'/g,
  /\bsubtitle:\s*'((?:\\.|[^'\\])*)'/g,
  /\blocation:\s*'((?:\\.|[^'\\])*)'/g,
  /\bdescription:\s*'((?:\\.|[^'\\])*)'/g,
  /\bheadline:\s*'((?:\\.|[^'\\])*)'/g,
  /\bsocialProof:\s*'((?:\\.|[^'\\])*)'/g,
  /\bwhySpecial:\s*'((?:\\.|[^'\\])*)'/g,
  /\bbestTime:\s*'((?:\\.|[^'\\])*)'/g,
  /\bcrowdLevel:\s*'((?:\\.|[^'\\])*)'/g,
  /\binsiderTip:\s*'((?:\\.|[^'\\])*)'/g,
  /\blocalOnlyNote:\s*'((?:\\.|[^'\\])*)'/g,
  /\bemotionalHook:\s*'((?:\\.|[^'\\])*)'/g,
  /\bbestTimeToGo:\s*'((?:\\.|[^'\\])*)'/g,
  /\binsiderTips:\s*'((?:\\.|[^'\\])*)'/g,
  /\bcostRange:\s*'((?:\\.|[^'\\])*)'/g,
  /\bdateRange:\s*'((?:\\.|[^'\\])*)'/g,
  /\bweatherWindow:\s*'((?:\\.|[^'\\])*)'/g,
  /\bliveWeatherNote:\s*'((?:\\.|[^'\\])*)'/g,
  /\bnextExperience:\s*'((?:\\.|[^'\\])*)'/g,
  /\bsunsetWindow:\s*'((?:\\.|[^'\\])*)'/g,
  /\btimelineSnapshot:\s*'((?:\\.|[^'\\])*)'/g,
  /\btime:\s*'((?:\\.|[^'\\])*)'/g,
  /\bcategory:\s*'((?:\\.|[^'\\])*)'/g,
  /\bemotionalLine:\s*'((?:\\.|[^'\\])*)'/g,
];

function extractCatalogStrings(source) {
  const out = new Set();
  for (const regex of FIELD_PATTERNS) {
    let match;
    while ((match = regex.exec(source)) !== null) {
      const raw = match[1]
        .replace(/\\n/g, '\n')
        .replace(/\\'/g, "'")
        .replace(/\\\\/g, '\\');
      const value = raw.trim();
      if (!value) continue;
      if (value.length < 2) continue;
      if (!/[A-Za-z]/.test(value)) continue;
      if (/^https?:\/\//i.test(value)) continue;
      out.add(value);
    }
  }
  return out;
}

async function translateText(text) {
  const url = new URL('https://translate.googleapis.com/translate_a/single');
  url.searchParams.set('client', 'gtx');
  url.searchParams.set('sl', 'en');
  url.searchParams.set('tl', 'ru');
  url.searchParams.set('dt', 't');
  url.searchParams.set('q', text);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = await res.json();
  return data[0].map((part) => part[0]).join('');
}

const phrases = new Set();
for (const rel of targets) {
  const abs = path.join(root, rel);
  const content = fs.readFileSync(abs, 'utf8');
  for (const s of extractCatalogStrings(content)) {
    phrases.add(s);
  }
}

const sorted = [...phrases].sort((a, b) => a.localeCompare(b));
const translated = new Map();

for (let i = 0; i < sorted.length; i += 1) {
  const src = sorted[i];
  try {
    const ru = await translateText(src);
    translated.set(src, ru);
  } catch {
    translated.set(src, src);
  }
  if ((i + 1) % 20 === 0) {
    process.stdout.write(`translated ${i + 1}/${sorted.length}\r`);
  }
}

const lines = [
  '// Auto-generated by tool/generate_ru_catalog_translations.mjs',
  '// ignore_for_file: lines_longer_than_80_chars',
  '',
  'const ruCatalogTranslations = <String, String>{',
];
for (const src of sorted) {
  const key = JSON.stringify(src).replace(/\$/g, '\\$');
  const value = JSON.stringify(translated.get(src)).replace(/\$/g, '\\$');
  lines.push(`  ${key}: ${value},`);
}
lines.push('};', '');
fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log(`\nWrote ${outPath} with ${sorted.length} entries`);
